[workspace]
members = [
  "apps/cli",
  "crates/core",
  "crates/extra",
  "crates/plugin-anchor",
  "crates/plugin-blockquote",
  "crates/plugin-cite",
  "crates/plugin-codeblock-syntect",
  "crates/plugin-custom",
  "crates/plugin-dialog",
  "crates/plugin-directive",
  "crates/plugin-extract-heading",
  "crates/plugin-heading",
  "crates/plugin-img",
  "crates/plugin-latex",
  "crates/plugin-list",
  "crates/plugin-markdown",
  "crates/plugin-marker",
  "crates/plugin-micromatter",
  "crates/plugin-quiz",
  "crates/plugin-section",
  "crates/plugin-table",
  "crates/plugin-vicado",
  "crates/plugin-wiki",
  "crates/renderer-ast",
  "crates/renderer-events",
  "crates/renderer-html",
  "crates/renderer-json",
  "crates/renderer-solid",
  "crates/tui",
]
resolver = "2"

[profile.release]
# Modern yet stable release profile tuned for small binaries
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
