[[task]]
name = "Plugin Heading Demo Solid"
input = "./src/heading.md"
output = "./out/heading.jsx"
plugin = "micromatter,markdown,sectionize,extract-heading,heading"
format = "solid"

[task.heading]
auto_number = true
number_style = "nested-number"

[task.heading.custom.heading]
name = "DocHeading"
template = "<DocHeading level={{attrs.level}} id=\"{attrs.id}\" class=\"{attrs.class}\" number=\"{attrs.number}\" qux={{attrs.qux}} nor={{attrs.nor}} >{children}</DocHeading>"

[[task.heading.custom.heading.imports]]
module = "@/components/DocHeading"
default = "DocHeading"

# === Normal

[[task]]
name = "Normal Demo Solid"
input = "./src/normal.md"
output = "./out/normal.jsx"
plugin = "micromatter,markdown,sectionize,extract-heading"
format = "solid"
