[[task]]
name = "Dialog Demo (HTML)"
input = "./src/[slug].md"
output = "./out/[slug].html"
plugin = "micromatter,img,dialog,markdown"
format = "html"
pretty = true
markdown_allow_html = true

[[task]]
name = "Dialog Demo (Solid)"
input = "./src/[slug].md"
output = "./out/[slug].jsx"
plugin = "micromatter,img,dialog,markdown"
format = "solid"
pretty = true
markdown_allow_html = true
